- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add backports repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian bullseye-backports main"
    state: present
    update_cache: true

- name: Install golang
  package:
    name: "{{ snowflake_packages_deb }}"
    default_release: bullseye-backports
    state: present

- name: Install required software
  package:
    name: "{{ snowflake_utils }}"
    state: present

- name: Add the user
  ansible.builtin.user:
    name: "{{ snowflake_user }}"
    create_home: true
    state: present

- name: Clone snowflake repo
  ansible.builtin.git:
    repo: 'https://git.torproject.org/pluggable-transports/snowflake.git'
    dest: /home/{{ snowflake_user }}/repo
    update: "{{ snowflake_update }}"
  register: clone_git

- name: go get
  ansible.builtin.command: go get
  args:
    chdir: /home/{{ snowflake_user }}/repo/proxy
  register: go_get
  when: clone_git is changed

- name: go build
  ansible.builtin.command: go build
  args:
    chdir: /home/{{ snowflake_user }}/repo/proxy
  register: go_build
  when: clone_git is changed

- name: Copy binary file to /usr/bin/
  ansible.builtin.copy:
    src: /home/{{ snowflake_user }}/repo/proxy/proxy
    dest: /usr/bin/
    mode: a+x
    remote_src: yes

- name: Add unit systemd
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - snowflake-proxy.service

- name: Enable service snowflake-proxy
  ansible.builtin.systemd:
    name: snowflake-proxy
    enabled: yes

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start/restart service snowflake
  ansible.builtin.service:
    name: snowflake-proxy
    state: restarted
